name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - name: Debug release output
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "Release created: ${{ steps.release.outputs.release_created }}"
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"
          echo "HTML URL: ${{ steps.release.outputs.html_url }}"
          echo "Tag name: ${{ steps.release.outputs.tag_name }}"
          echo "Major: ${{ steps.release.outputs.major }}"
          echo "Minor: ${{ steps.release.outputs.minor }}"
          echo "Patch: ${{ steps.release.outputs.patch }}"

  # Add a job to trigger the publish workflow when a release is created
  trigger-publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}

      - name: Trigger publish workflow
        run: |
          echo "Release was created, tag name is ${{ needs.release-please.outputs.tag_name }}"
          echo "This should trigger the publish workflow automatically"
