name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - name: Debug release output
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "Release created: ${{ steps.release.outputs.release_created }}"
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"
          echo "HTML URL: ${{ steps.release.outputs.html_url }}"
          echo "Tag name: ${{ steps.release.outputs.tag_name }}"
          echo "Major: ${{ steps.release.outputs.major }}"
          echo "Minor: ${{ steps.release.outputs.minor }}"
          echo "Patch: ${{ steps.release.outputs.patch }}"

  trigger-publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger publish workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = '${{ needs.release-please.outputs.tag_name }}';
            console.log(`Triggering publish workflow with tag: ${tag}`);

            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish.yml',
              ref: 'main',
              inputs: {
                tag_name: tag
              }
            });
